Feature: Signup Form 

  Scenario: TC#1 : Simple Checking of Signup Form
    When I open website "http://192.168.20.4"
    And I touch "Login / Register"
    #And I wait for 5 seconds
    Then I see the text "Login to Moneytree"
    And I type "Administrator" into id "login_email"
    And I type "@ppl31C3bu" into id "login_password"
    And I touch "Login"
    #And I wait for 2 seconds
    Then I see the text "Guided by stability, focused on your growth."
    #And I wait for 2 seconds
    And I open a new tab and go to link "http://192.168.20.4/application-form-(moneytree)/new"
    #And I wait for 2 seconds
    
    And I find the text "New Loan Application Form"
    And I find the text "Application Stage"
    And I find the text "Save as Draft"
    And I find the text "Continue Later"
    And I find the text "Official Application"
    And I find the text "Last Name"
    And I find the text "First Name"
    And I find the text "Middle Name"
    And I find the text "Status"
    And I find the text "Birthday"
    And I find the text "Education"
    And I find the text "Email Address"
    And I find the text "Mobile No."
    And I find the text "Phone No."
    And I find the text "Present Address"
    And I find the text "Home Address"
    And I find the text "Provincial Address"
    And I find the text "Residency"
    And I find the text "Spouse's Name"
    And I find the text "No of Dependents"
    And I find the text "FB Email Address (If any)"
    #And I find the text "Monthly Income"
    And I open the form section "Monthly Income"
    #And I see the button "Monthly Income"
    And I find the text "Monthly Income / Salary"
    And I find the text "Spouse's Income / Salary"
    And I find the text "Other Income From (specify as many and its income)"
    And I find the text "Total Monthly Income"
    And I find the text "Fixed Obligations"
    And I find the text "Other Living Expenses"
    And I find the text "Net Monthly Income"
    And I open the form section "Employment / Business"
    And I find the text "Primary Employment Status"
    And I find the text "Employer / Business Address"
    And I find the text "How long on the job / Business"
    And I find the text "Employer / Business Phone"
    And I find the text "Previous Employer"
    And I find the text "Business Address of Previous Employer"
    And I open the form section "Spouse"
    And I find the text "Spouse's Employer / Business Name"
    And I find the text "Years of Employment"
    And I find the text "Spouse's Employer / Business Address"
    And I find the text "Telephone No."
    And I find the text "Position"
    And I find the text "Spouse's Home address If different from applicant's address"
    And I open the form section "Dependents References"
    And I find the text "Dependents"
    And I open the form section "Nearest Relative Not Living with you"
    And I find the text "First Relative"
    And I find the text "Second Relative"
    And I find the text "Address"
    And I find the text "Address"
    And I find the text "Telephone No."
    And I find the text "Telephone No."
    And I open the form section "Personal References"
    And I find the text "First Personal Reference"
    And I find the text "Second Personal Reference"
    And I find the text "Third Personal Reference"
    And I find the text "Address"
    And I find the text "Address"
    And I find the text "Address"
    And I find the text "Telephone No."
    And I find the text "Telephone No."
    And I find the text "Telephone No."
    And I open the form section "Credit Reference"
    And I find the text "First Credit Reference"
    And I find the text "Second Credit Reference"
    And I find the text "Third Credit Reference"
    And I find the text "Address"
    And I find the text "Address"
    And I find the text "Address"
    And I find the text "Type of Loan"
    And I find the text "Type of Loan"
    And I find the text "Type of Loan"
    And I find the text "Monthly Payment"
    And I find the text "Monthly Payment"
    And I find the text "Monthly Payment"
    And I find the text "Outstanding Balance"
    And I find the text "Outstanding Balance"
    And I find the text "Outstanding Balance"
    And I find the text "Credit Card"
    And I find the text "Current Account At"
    And I find the text "Last Financing By"
    And I find the text "Savings Account At"
    And I open the form section "Credit Reference"
    And I find the text "Tin"
    And I find the text "SSS No."
    And I find the text "Res. Cert"
    And I find the text "Res. Cert - Issued at"
    And I find the text "Res. Cert - Date"
    And I find the text "ACR No."
    And I find the text "ACR No. - Issued at"
    And I find the text "ACR No. - Date"
    And I find the text "Verification OR No."
    And I find the text "Verification OR No. - Date"
    And I open the form section "Loan"
    And I find the text "Purpose of Loan"
    And I find the text "Desired Loan Amount"
    And I find the text "Term of Loan"
    And I find the text "Expected Monthly Payment"
    And I open the form section "Required Documents"
    And I find the text "Photocopy of at least two valid IDs (i.e. Company ID and Government issued ID)"
    And I find the text "Photocopy of at least two valid ID's of spouse, if married"
    And I find the text "Certificate of Employment with Compensation"
    And I find the text "Payslips (Latest 2 month)"
    And I find the text "Residence Sketch (Google Maps is not accepted)"
    And I find the text "Terms and Condition"
    And I find the text "I acknowledge that I have read and agree to the terms."
    And I find the text "Discard"
    And I find the text "Save"
    And I wait for 2 seconds
